### PR TITLE
0.4.0

### PR DESCRIPTION
**Pull request by auguwu**
# Roadmap
* Inhibitors
* Database Providers
* Argument Types
* Argument Parser system
* Making events, tasks, and inhibitors optional.
  * Events: You can use `CommandoClient#on` in the main bot's process
  * Tasks: people dont need tasks owo
  * Inhibitors: people don't need inhibitors for anything

### CODE REVIEW

**Comment by davidcralph** [comment]
owo yes

**Comment by auguwu** [comment]
just waiting until I can do it by December 25th OwO

**Comment by auguwu** [comment]
Removed from roadmap:
- Database Providers
- Localization
- Ability to use events in main bot process

**Comment by auguwu** [comment]
@ohlookitsderpy send coffee pls pl0x

**Comment by auguwu** [comment]
almost up! (6 more days >w<)
when i get out of school, i will work on this owo

**Comment by davidcralph** [comment]
pings

**Comment by davidcralph** [comment]
disgusting

**Comment by auguwu** [comment]
no u weeb

**Comment by davidcralph** [comment]
ur weeb

**Comment by auguwu** [comment]
ik :D

**Pull request merged**
